In [1]:
 import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [5]:
data={"color":["green","yellow","orange","red","blue"]}
df=pd.DataFrame(data)
df

    color
0   green
1  yellow
2  orange
3     red
4    blue

In [9]:
label_en=LabelEncoder()
df['Color_label']=label_en.fit_transform(df['color'])
df.head()

    color  Color_label
0   green            1
1  yellow            4
2  orange            2
3     red            3
4    blue            0

In [11]:
one_hot_en=OneHotEncoder(sparse_output=False)
one_hot_array=one_hot_en.fit_transform(df[['color']])
one_hot_df=pd.DataFrame(one_hot_array,columns=one_hot_en.get_feature_names_out())
df=pd.concat([df,one_hot_df],axis=1)
df

,color,Color_label,color_blue,color_green,color_orange,color_red,color_yellow
0,green,1,0.0,1.0,0.0,0.0,0.0
1,yellow,4,0.0,0.0,0.0,0.0,1.0
2,orange,2,0.0,0.0,1.0,0.0,0.0
3,red,3,0.0,0.0,0.0,1.0,0.0
4,blue,0,1.0,0.0,0.0,0.0,0.0